### ISSUE TITLE
Jest Reporter: Error - thrown when all tests are skipped in a file

### ISSUE THREAD

**Issue by thomaschaplin** [mtkennerly/kelonio#5]
GIVEN I am using `benchmark.record()` in a jest test
AND I have skipped all the tests in a test file by using `describe.skip()` or `xdescribe()`
WHEN I run the tests
THEN I get an error (see below code snippet)

Example of skipped tests:
```
import { benchmark } from "kelonio";

describe.skip("A Jest test", () => {
    it("can use Kelonio with a simple description", async () => {
        await benchmark.record("simple description", () => { });
    });

    it("can use Kelonio with a nested description", async () => {
        await benchmark.record(["nested", "description"], () => { }, { minUnder: 0 });
    });
});

```

Example output when all tests are skipped in a test file:
```
Test Suites: 1 skipped, 0 of 1 total
Tests:       2 skipped, 2 total
Snapshots:   0 total
Time:        1.419s, estimated 2s
Error: The Kelonio reporter for Jest requires benchmark serialization. Make sure to call `JestReporter.initializeKelonio()`.
    at JestReporter.onRunComplete (/Users/thomaschaplin/GIT/thomaschaplin/kelonio/src/reporters.ts:45:19)
    at /Users/thomaschaplin/GIT/thomaschaplin/kelonio/examples/jest/node_modules/@jest/core/build/ReporterDispatcher.js:200:29
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/thomaschaplin/GIT/thomaschaplin/kelonio/examples/jest/node_modules/@jest/core/build/ReporterDispatcher.js:10:24)
    at _next (/Users/thomaschaplin/GIT/thomaschaplin/kelonio/examples/jest/node_modules/@jest/core/build/ReporterDispatcher.js:30:9)
npm ERR! Test failed.  See above for more details.
```

Note: This can be reproduced if you skip the top level describe in `/examples/jest/index.test.ts`

**Comment by thomaschaplin** [comment]
@mtkennerly I've been investigating this issue and currently looking into a solution but yet to find one. I believe a check needs to be done to see if a test is marked as skipped or not and maybe return so no errors are thrown.

**Comment by thomaschaplin** [comment]
Further to my investigation, if a test file does not use `kelonio` at all then this error occurs also.
